# setfacl -m u:www-data:rx example.org
- name: Grant www-data user access to the parent folder
  acl:
    path: "{{ webroot }}/.."
    entity: www-data
    etype: user
    permissions: rx
    state: present
    recalculate_mask: no_mask
  when: run_as_user != ansible_user

# setfacl --recursive -m u:www-data:rx example.org/web
- name: Grant www-data user access to the webroot
  acl:
    path: "{{ webroot }}"
    entity: www-data
    etype: user
    permissions: rx
    recursive: yes
    state: present
    recalculate_mask: no_mask
  when: run_as_user != ansible_user

# setfacl --default --no-mask --recursive -m u:www-data:rx example.org/web
- name: Set default ACLs for files under the webroot
  acl:
    path: "{{ webroot }}"
    entity: www-data
    etype: user
    permissions: rx
    recursive: yes
    default: yes
    state: present
    recalculate_mask: no_mask
  when: run_as_user != ansible_user

# setfacl --default --no-mask --recursive -m g::rwX example.org/web
- name: Set default ACLs for files under the webroot
  acl:
    path: "{{ webroot }}"
    entity: "{{ run_as_user }}"
    etype: group
    permissions: rwX
    recursive: yes
    default: yes
    state: present
    recalculate_mask: no_mask
  when: run_as_user != ansible_user

  # setfacl --no-mask --recursive -m g::rwX example.org/web
- name: Set ACLs for files under the webroot
  acl:
    path: "{{ webroot }}"
    entity: "{{ run_as_user }}"
    etype: group
    permissions: rwX
    recursive: yes
    state: present
    recalculate_mask: no_mask
  when: run_as_user != ansible_user

  # setfacl --mask --recursive -m m::r-x example.org/web
- name: Set default mask correctly
  acl:
    path: "{{ webroot }}"
    etype: mask
    permissions: rx
    recursive: yes
    state: present
    recalculate_mask: mask
  when: run_as_user != ansible_user

- name: Set file owner
  file:
    path: "{{ webroot }}"
    owner: "{{ run_as_user }}"
    group: "{{ run_as_user }}"
    recurse: yes
  when: run_as_user != ansible_user

- name: Find all directories
  find:
    paths: "{{ webroot }}"
    file_type: directory
  register: directories

- name: Set sticky bit and execute on directories
  file:
    path: "{{ item.path }}"
    mode: g+xs
  with_items: "{{ directories.files }}"

- name: Find all static assets
  find:
    paths: "{{ webroot }}"
    patterns: '*.js,*.css,*.pdf,*.jpeg,*.jpg,*.gif,*.html,*.ico'
  register: static_assets

- debug:
   var: static_assets

- name: Make assets world-readable
  file:
    path: "{{ item.path }}"
    mode: ugo+r
  with_items: "{{ static_assets.files }}"
