# setfacl -m u:www-data:rx example.org
- name: Grant www-data user access to the parent folder
  acl:
    path: "{{ webroot }}/.."
    entity: www-data
    etype: user
    permissions: rx
    state: present
    recalculate_mask: no_mask
  become_user: root
  tags: acl

# setfacl --recursive -m u:www-data:rx example.org/web
- name: Grant www-data user access to the webroot
  acl:
    path: "{{ webroot }}"
    entity: www-data
    etype: user
    permissions: rx
    recursive: yes
    state: present
    recalculate_mask: no_mask
  become_user: root
  tags: acl

# setfacl --default --no-mask --recursive -m u:www-data:rx example.org/web
- name: Set default ACLs for files under the webroot
  acl:
    path: "{{ webroot }}"
    entity: www-data
    etype: user
    permissions: rx
    recursive: yes
    default: yes
    state: present
    recalculate_mask: no_mask
  become_user: root
  tags: acl

# Also maybe:
# setfacl --no-mask --recursive -m g::rwx example.org/web

- name: Set file owner
  file:
    dest: "{{ webroot }}"
    owner: "{{ run_as_user }}"
    group: "{{ run_as_user }}"
    recurse: yes
  become_user: root
